
# Application
spring.application.name=Stockflow

spring.datasource.url=${JDBC_URL:jdbc:postgresql://localhost:5432/stockflow_db}
spring.datasource.username=${JDBC_USERNAME:postgres}
spring.datasource.password=${JDBC_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080

logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=INFO

# OAuth2 Resource Server (JWT Configuration)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/logistics-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/logistics-realm/protocol/openid-connect/certs

# Keycloak Admin Client Configuration
keycloak.server-url=http://localhost:8180
keycloak.realm=logistics-realm
keycloak.admin-client-id=admin-cli
keycloak.admin-username=amina_admin
keycloak.admin-password=123456
keycloak.api-client-id=stockflow-api
keycloak.api-client-secret=ylsLfADw4qodnRg9FSbflUPvEIktk2Qe